server:
  port: ${PORT:8080}

spring:
  mustache:
    check-template-location: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/booker}
#    username: ${SPRING_DATASOURCE_USERNAME:user}
#    password: ${SPRING_DATASOURCE_PASSWORD:password}

vaadin:
  pnpm:
    enable: false

logging:
  level: org.atmosphere=warn

app:
  root-path: https://mhsn-booker.herokuapp.com
  root-mail: booker@app.dro
