server:
  port: ${PORT:8080}

spring:
  mustache:
    check-template-location: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/booker}
#    username: ${SPRING_DATASOURCE_USERNAME:user}
#    password: ${SPRING_DATASOURCE_PASSWORD:password}

vaadin:
  pnpm:
    enable: false

logging:
  level: org.atmosphere=warn

#Custom
app:
  root:
    mail: booker@app.dro
    url: https://getpass.herokuapp.com/
