server:
  port: ${PORT:8080}

spring:
  mustache:
    check-template-location: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

vaadin:
  pnpm:
    enable: false

logging:
  level: org.atmosphere=warn

app:
  root-path: http://localhost:8080

