server:
  port: ${PORT:8080}

spring:
  mustache:
    check-template-location: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookerapp
    password:
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

vaadin:
  pnpm:
    enable: false

logging:
  level: org.atmosphere=warn

#Custom
app:
  root:
    mail: booker@app.dro
    url: http://localhost:8080/

